### ISSUE TITLE
rm -r -f reports "node has children"

### ISSUE THREAD

**Issue by gengmao** [davidledwards/zookeeper#18]
I have a parent node which has 3 children nodes - each has some data in it. I expected `rm -r -f` can remove the parent node along with all its children, however it didn't. It just reported "node has children" like below. 
```
zk> ls /healthCompact/mao-zk-1
depman
gyoji
health
zk> rm -r -f /healthCompact/mao-zk-1
/healthCompact/mao-zk-1: node has children
```
Is the expectation wrong?

**Comment by gengmao** [comment]
Never mind. It is my mistake. These child nodes are ephemeral and their sessions are alive. Hence they couldn't be removed. Normally `rm -r -f` works as expected.

**Comment by davidledwards** [comment]
Good point about the ephemeral nodes. I should probably mention this scenario in the command help.
