### ISSUE TITLE
Scala 2.12 version ?

### ISSUE THREAD

**Issue by nicolasdalsass** [davidledwards/zookeeper#21]
Hi !
Do you plan on publishing a scala 2.12 compatible version ? 
Thanks :-)

**Comment by davidledwards** [comment]
Yes, I was planning after the first person nudged me. I will work on getting something released soon.

**Comment by nicolasdalsass** [comment]
That's extra nice of you :-) Thanks !

**Comment by davidledwards** [comment]
You can follow issue #22.

**Comment by davidledwards** [comment]
Note that a new version has been released that supports Scala 2.12.

https://github.com/davidledwards/zookeeper/tree/release-1.4
