### ISSUE TITLE
superfluous output in command mode

### ISSUE THREAD

**Issue by tamboril** [davidledwards/zookeeper#24]
When I use `zk` in command mode (with `-c`), to get the content of a node
and pipe it through another command (such as `jq`), I have to filter out the 
"connecting to..." message.

Maybe that message should be suppressed when `-c` is used.

**Comment by davidledwards** [comment]
Good suggestion. A simple workaround is to use the `-q` option to suppress the gratuitous console output.

```
zk -q -c ... | ...
```

**Comment by tamboril** [comment]
Great.  I didn't know about that one.

**Comment by davidledwards** [comment]
Fixed in [1.4.1](https://github.com/davidledwards/zookeeper/tree/release-1.4.1).

When `-c` is specified, unnecessary console messages are now suppressed, thus not requiring `-q`.
