### ISSUE TITLE
Implement Zookeeper Persitent/Persistent-Recursive watches

### ISSUE THREAD

**Issue by P4ndaFR** [davidledwards/zookeeper#32]
Hi,

I would be interested in being able to use Persistent-Recursive watch within your library.
This feature (introduced in Zookeeper 3.6) allows to set watches that does not expires upon 1 event, and (in the case of Persistent-recursive) allows to receive details of a change within a znode's tree, see: https://zookeeper.apache.org/doc/r3.8.4/zookeeperProgrammers.html#sc_WatchPersistentRecursive

Since the zookeeper java API allows to set this watch with the [addWatch](https://zookeeper.apache.org/doc/r3.8.4/apidocs/zookeeper-server/org/apache/zookeeper/ZooKeeper.html#addWatch(java.lang.String,org.apache.zookeeper.Watcher,org.apache.zookeeper.AddWatchMode)) function, I think it should be pretty straightforward to implement it within your SynchronousWatchableZK/AsynchronousWatchableZK classes.

I can submit a PR if you are interested.

**Comment by davidledwards** [comment]
Yes, please submit the PR. I have not been active on this project for several years, so I'm happy to accept contributions.

**Comment by P4ndaFR** [comment]
Ok, i'm on it.

**Comment by davidledwards** [comment]
See issue #34. I released 1.7 yesterday. The artifacts are available on the Maven central repo.

**Comment by P4ndaFR** [comment]
Thank you.
